-- Verify schemas/faker/procedures/utils  on pg

BEGIN;

SELECT assert_function('faker.word_type()'::regprocedure);
SELECT assert_function('faker.word(text)'::regprocedure);
SELECT assert_function('faker.word(text[])'::regprocedure);
SELECT assert_function('faker.gender(text)'::regprocedure);
SELECT assert_function('faker.username()'::regprocedure);
SELECT assert_function('faker.name(text)'::regprocedure);
SELECT assert_function('faker.surname()'::regprocedure);
SELECT assert_function('faker.fullname(text)'::regprocedure);
SELECT assert_function('faker.business()'::regprocedure);
SELECT assert_function('faker.city(text)'::regprocedure);
SELECT assert_function('faker.zip(text)'::regprocedure);
SELECT assert_function('faker.lnglat(float8, float8, float8, float8)'::regprocedure);
SELECT assert_function('faker.lnglat(text)'::regprocedure);
SELECT assert_function('faker.phone()'::regprocedure);
SELECT assert_function('faker.street()'::regprocedure);
SELECT assert_function('faker.state(text)'::regprocedure);
SELECT assert_function('faker.address(text, text)'::regprocedure);
SELECT assert_function('faker.tags(int4, int4, text)'::regprocedure);
SELECT assert_function('faker.sentence(text, int4, int4, text[], text)'::regprocedure);
SELECT assert_function('faker.paragraph(text, int4, int4, text[])'::regprocedure);
SELECT assert_function('faker.email()'::regprocedure);
SELECT assert_function('faker.uuid()'::regprocedure);
SELECT assert_function('faker.token(int4)'::regprocedure);
SELECT assert_function('faker.password()'::regprocedure);
SELECT assert_function('faker.hostname()'::regprocedure);
SELECT assert_function('faker.time_unit()'::regprocedure);
SELECT assert_function('faker.float(float8, float8)'::regprocedure);
SELECT assert_function('faker.integer(int4, int4)'::regprocedure);
SELECT assert_function('faker.date(int4, int4, bool)'::regprocedure);
SELECT assert_function('faker.birthdate(int4, int4)'::regprocedure);
SELECT assert_function('faker.interval()'::regprocedure);
SELECT assert_function('faker.interval(int4, int4)'::regprocedure);
SELECT assert_function('faker.boolean()'::regprocedure);
SELECT assert_function('faker.timestamptz(bool)'::regprocedure);
SELECT assert_function('faker.mime()'::regprocedure);
SELECT assert_function('faker.ext(text)'::regprocedure);
SELECT assert_function('faker.image_mime()'::regprocedure);
SELECT assert_function('faker.image(int4, int4)'::regprocedure);
SELECT assert_function('faker.profilepic()'::regprocedure);
SELECT assert_function('faker.profilepic(text)'::regprocedure);
SELECT assert_function('faker.file(text)'::regprocedure);
SELECT assert_function('faker.url(text)'::regprocedure);
SELECT assert_function('faker.upload(text)'::regprocedure);
SELECT assert_function('faker.ip(text)'::regprocedure);
SELECT assert_function('faker.attachment(text)'::regprocedure);

ROLLBACK;
