-- Revert schemas/faker/procedures/utils from pg

BEGIN;

DROP FUNCTION faker.attachment(text);
DROP FUNCTION faker.ip(text);
DROP FUNCTION faker.upload(text);
DROP FUNCTION faker.url(text);
DROP FUNCTION faker.file(text);
DROP FUNCTION faker.profilepic(text);
DROP FUNCTION faker.profilepic();
DROP FUNCTION faker.image(int4, int4);
DROP FUNCTION faker.image_mime();
DROP FUNCTION faker.ext(text);
DROP FUNCTION faker.mime();
DROP FUNCTION faker.timestamptz(bool);
DROP FUNCTION faker.boolean();
DROP FUNCTION faker.interval(int4, int4);
DROP FUNCTION faker.interval();
DROP FUNCTION faker.birthdate(int4, int4);
DROP FUNCTION faker.date(int4, int4, bool);
DROP FUNCTION faker.integer(int4, int4);
DROP FUNCTION faker.float(float8, float8);
DROP FUNCTION faker.time_unit();
DROP FUNCTION faker.hostname();
DROP FUNCTION faker.password();
DROP FUNCTION faker.token(int4);
DROP FUNCTION faker.uuid();
DROP FUNCTION faker.email();
DROP FUNCTION faker.paragraph(text, int4, int4, text[]);
DROP FUNCTION faker.sentence(text, int4, int4, text[], text);
DROP FUNCTION faker.tags(int4, int4, text);
DROP FUNCTION faker.address(text, text);
DROP FUNCTION faker.state(text);
DROP FUNCTION faker.street();
DROP FUNCTION faker.phone();
DROP FUNCTION faker.lnglat(text);
DROP FUNCTION faker.lnglat(float8, float8, float8, float8);
DROP FUNCTION faker.zip(text);
DROP FUNCTION faker.city(text);
DROP FUNCTION faker.business();
DROP FUNCTION faker.fullname(text);
DROP FUNCTION faker.surname();
DROP FUNCTION faker.name(text);
DROP FUNCTION faker.username();
DROP FUNCTION faker.gender(text);
DROP FUNCTION faker.word(text[]);
DROP FUNCTION faker.word(text);
DROP FUNCTION faker.word_type();

COMMIT;
